import { adminDb } from "./firebase-admin";
import { Timestamp } from "firebase-admin/firestore";

async function importApril2026() {
  // Delete all existing data first
  console.log("Deleting existing figures...");
  const existing = await adminDb.collection("figures").get();
  const deleteOps = existing.docs.map((doc) => doc.ref.delete());
  await Promise.all(deleteOps);
  console.log(`Deleted ${existing.docs.length} existing figures.`);

  const now = Timestamp.now();
  const src = "https://tokutame.net/prize-matome-202604/";

  const figures = [
    // 4月3日
    {
      nameKo: "오버로드 알베도 버니 화이트 Ver.",
      nameEn: "Overlord Albedo Bunny White Ver.",
      nameJa: "『オーバーロード』アルベド バニー ホワイトVer.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-overlord-system1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 3)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "그리드맨 유니버스 타카라다 릿카 이스터 버니 ver.",
      nameEn: "SSSS.Gridman Universe Takarada Rikka Easter Bunny ver.",
      nameJa: "『グリッドマン ユニバース』宝多六花 イースターバニーver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-ssssgridman-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 3)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "헌터×헌터 노부나가",
      nameEn: "HUNTER×HUNTER Nobunaga",
      nameJa: "『HUNTER×HUNTER』ノブナガ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-hunter-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 3)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月4日
    {
      nameKo: "데스노트 야가미 라이토",
      nameEn: "DEATH NOTE Yagami Light",
      nameJa: "『DEATH NOTE』夜神月",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-deathnote-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 4)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "리제로 프리실라&알데바란 GiGO 한정",
      nameEn: "Re:Zero Priscilla & Aldebaran GiGO Exclusive",
      nameJa: "『Re:ゼロ』プリシラ&アルデバラン GiGO限定",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-rezero-gigo1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 4)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月8日
    {
      nameKo: "울트라맨 피그몬",
      nameEn: "Ultraman Pigmon",
      nameJa: "『ウルトラマン』ピグモン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-ultraman-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "이웃집 천사님 시이나 마히루 원피스 ver.",
      nameEn: "The Angel Next Door Shiina Mahiru One-Piece ver.",
      nameJa: "『お隣の天使様』椎名真昼 ワンピースver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-otonarinotenshisama-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "산리오 캐릭터즈 미니 피규어 후르츠 파티",
      nameEn: "Sanrio Characters Mini Figure Fruits Party",
      nameJa: "『サンリオキャラクターズ』ミニフィギュア フルーツパーティ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-sanrio-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "준다몬 준다몬",
      nameEn: "Zundamon Zundamon",
      nameJa: "『ずんだもん』ずんだもん",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-zundamon-furyu2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "장송의 프리렌 볼받침 흉상 피규어 프리렌",
      nameEn: "Frieren: Beyond Journey's End Bust Figure Frieren",
      nameJa: "『葬送のフリーレン』ほおづえ胸像フィギュア フリーレン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-frieren-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "장송의 프리렌 Trio-Try-iT 프리렌",
      nameEn: "Frieren: Beyond Journey's End Trio-Try-iT Frieren",
      nameJa: "『葬送のフリーレン』Trio-Try-iT フリーレン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-frieren-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "체인소맨 레제편 Noir Edge Collection 체인소맨",
      nameEn: "Chainsaw Man Reze Arc Noir Edge Collection Chainsaw Man",
      nameJa: "『チェンソーマン レゼ篇』Noir Edge Collection チェンソーマン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-chainsawman-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "도호 괴수 고지라 (2001)",
      nameEn: "Toho Monster Godzilla (2001)",
      nameJa: "『東宝怪獣』ゴジラ（2001）",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-toho-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "닥터 스톤 이시가미 센쿠·나나미 류스이·아사기리 겐",
      nameEn: "Dr.STONE Ishigami Senku, Nanami Ryusui & Asagiri Gen",
      nameJa: "『Dr.STONE』石神千空・七海龍水・あさぎりゲン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-drstone-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "카이지 철골 건너기 피규어",
      nameEn: "Kaiji Steel Beam Crossing Figure",
      nameJa: "『カイジ』鉄骨渡りフィギュア",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-kaiji-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "드래곤볼Z 초사이어인 손고한",
      nameEn: "Dragon Ball Z Super Saiyan Son Gohan",
      nameJa: "『ドラゴンボールZ』超サイヤ人孫悟飯",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-dragonball-banpresto8.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "드래곤볼Z 초사이어인 손고텐",
      nameEn: "Dragon Ball Z Super Saiyan Son Goten",
      nameJa: "『ドラゴンボールZ』超サイヤ人孫悟天",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-dragonball-banpresto9.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "To LOVEru 후루테가와 유이 폴리스 ver.",
      nameEn: "To LOVEru Kotegawa Yui Police ver.",
      nameJa: "『To LOVEる』古手川唯 ポリスver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-toloveru-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 8)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月9日
    {
      nameKo: "울트라맨 메비우스 흉상 라이트",
      nameEn: "Ultraman Mebius Bust Light",
      nameJa: "『ウルトラマンメビウス』胸像ライト",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-ultraman-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "크레용 신짱 꿈틀꿈틀 신짱",
      nameEn: "Crayon Shin-chan Wiggling Shinnosuke",
      nameJa: "『クレヨンしんちゃん』くねくねしんちゃん",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-shinchan-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "NIKKE 프리바티 메이드 ver.",
      nameEn: "NIKKE Privaty Maid ver.",
      nameJa: "『NIKKE』プリバティ メイドver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-nikke-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "전생슬라임 리무루 실리콘 룸라이트",
      nameEn: "That Time I Got Reincarnated as a Slime Rimuru Silicone Room Light",
      nameJa: "『転スラ』リムル シリコンルームライト",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-tensura-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "To LOVEru 유우키 미칸",
      nameEn: "To LOVEru Yuuki Mikan",
      nameJa: "『To LOVEる』結城美柑",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-toloveru-furyu2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "나루토 데이다라&사스케",
      nameEn: "NARUTO Deidara & Sasuke",
      nameJa: "『NARUTO』デイダラ＆サスケ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-naruto-banpresto5.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "닌타마 란타로 자토 곤나몬",
      nameEn: "Nintama Rantaro Zatou Gonnaemon",
      nameJa: "『忍たま乱太郎』雑渡昆奈門",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-nintama-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "하이큐!! 코즈메 켄마·쿠로오 테츠로",
      nameEn: "Haikyu!! Kozume Kenma & Kuroo Tetsurou",
      nameJa: "『ハイキュー!!』孤爪研磨・黒尾鉄朗",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-haikyu-banpresto4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "하이큐!! 츠키시마 케이 룸라이트",
      nameEn: "Haikyu!! Tsukishima Kei Room Light",
      nameJa: "『ハイキュー!!』月島蛍 ルームライト",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-haikyu-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "하츠네 미쿠 빨간 드레스",
      nameEn: "Hatsune Miku Red Dress",
      nameJa: "『初音ミク』赤ドレス",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-hatsunemiku-furyu3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "포켓몬 몬스터볼 컬렉션 vol.2",
      nameEn: "Pokemon Monster Ball Collection vol.2",
      nameJa: "『ポケモン』モンスターボールコレクションvol.2",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-pokemon-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "마인크래프트 크리퍼 BIG",
      nameEn: "Minecraft Creeper BIG",
      nameJa: "『マインクラフト』クリーパーBIG",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-minecraft-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 루피 KING OF ARTIST SPECIAL",
      nameEn: "One Piece Luffy KING OF ARTIST SPECIAL",
      nameJa: "『ワンピース』ルフィ KING OF ARTIST SPECIAL",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto15.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 워콜레 갓밸리 사건 2",
      nameEn: "One Piece WCF God Valley Incident 2",
      nameJa: "『ワンピース』ワーコレ ゴッドバレー事件2",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-onepiece-banpresto7.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 피규어 라이트 패왕",
      nameEn: "One Piece Figure Light Hakok",
      nameJa: "『ワンピース』フィギュアライト 覇国",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto22.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 9)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月10日
    {
      nameKo: "귀멸의 칼날 토키토 무이치로 기둥 수련편",
      nameEn: "Demon Slayer Tokito Muichiro Hashira Training Arc",
      nameJa: "『鬼滅の刃』時透無一郎 柱稽古編",
      imageUrl: "https://tokutame.net/wp-content/uploads/2025/02/prize-20250314-kimetsu-sega1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "귀멸의 칼날 이구로 오바나이 기둥 수련편",
      nameEn: "Demon Slayer Iguro Obanai Hashira Training Arc",
      nameJa: "『鬼滅の刃』伊黒小芭内 柱稽古編",
      imageUrl: "https://tokutame.net/wp-content/uploads/2025/02/prize-20250314-kimetsu-sega2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "귀멸의 칼날 신타즈 사네미 기둥 수련편",
      nameEn: "Demon Slayer Shinazugawa Sanemi Hashira Training Arc",
      nameJa: "『鬼滅の刃』不死川実弥 柱稽古編",
      imageUrl: "https://tokutame.net/wp-content/uploads/2025/02/prize-20250314-kimetsu-sega3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "링 사다코",
      nameEn: "The Ring Sadako",
      nameJa: "『リング』貞子",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-sadako-furyu1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "주술회전 고조 사토루 무량공처",
      nameEn: "Jujutsu Kaisen Gojo Satoru Unlimited Void",
      nameJa: "『呪術廻戦』五条悟 無量空処",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-jujutsu-sega2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "To LOVEru 골든 다크니스 BiCute",
      nameEn: "To LOVEru Golden Darkness BiCute",
      nameJa: "『To LOVEる』金色の闇 BiCute",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-toloveru-furyu3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "명탐정 코난 에도가와 코난",
      nameEn: "Detective Conan Edogawa Conan",
      nameJa: "『名探偵コナン』江戸川コナン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-conan-sega1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "명탐정 코난 하기와라 치하야",
      nameEn: "Detective Conan Hagiwara Chihaya",
      nameJa: "『名探偵コナン』萩原千速",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-conan-sega3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "명탐정 코난 세라 마스미",
      nameEn: "Detective Conan Sera Masumi",
      nameJa: "『名探偵コナン』世良真純",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-conan-sega2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "명탐정 코난 하기와라 켄지",
      nameEn: "Detective Conan Hagiwara Kenji",
      nameJa: "『名探偵コナン』萩原研二",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-conan-sega4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 10)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月11日
    {
      nameKo: "슈퍼 마리오 테레사 반짝반짝 피규어",
      nameEn: "Super Mario Teresa (Boo) Glowing Figure",
      nameJa: "『スーパーマリオ』テレサ ぴかっとフィギュア",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-mario-taito1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 11)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "드래곤 퀘스트 PC 마우스 메탈슬라임&버블슬라임",
      nameEn: "Dragon Quest PC Mouse Metal Slime & Bubble Slime",
      nameJa: "『ドラゴンクエスト』PCマウス はぐれメタル&バブルスライム",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-draque-taito2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 11)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "무민 니요로니요로 스파이스 보틀",
      nameEn: "Moomin Hattifatteners Spice Bottle",
      nameJa: "『ムーミン』ニョロニョロ スパイスボトル",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-moomin-taito1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 11)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月14日
    {
      nameKo: "어몽어스 미니 피규어 vol.1",
      nameEn: "Among Us Mini Figure vol.1",
      nameJa: "『Among Us』ミニフィギュアvol.1",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-amongus-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "이웃집 천사님 시이나 마히루",
      nameEn: "The Angel Next Door Shiina Mahiru",
      nameJa: "『お隣の天使様』椎名真昼",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-otonarinotenshisama-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "크레이지 라쿤 Ras",
      nameEn: "Crazy Raccoon Ras",
      nameJa: "『Crazy Raccoon』Ras",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-cr-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "크레이지 라쿤 Uruca",
      nameEn: "Crazy Raccoon Uruca",
      nameJa: "『Crazy Raccoon』Uruca",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-cr-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "산리오 쿠로미&우사하나",
      nameEn: "Sanrio Kuromi & Usahana",
      nameJa: "『サンリオ』クロミ＆ウサハナ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-sanrio-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "디지몬 아구몬 피규어 라이트",
      nameEn: "Digimon Agumon Figure Light",
      nameJa: "『デジモン』アグモン フィギュアライト",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-digimon-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "드래곤볼 초 손오공 MATCH MAKERS",
      nameEn: "Dragon Ball Super Son Goku MATCH MAKERS",
      nameJa: "『ドラゴンボール超』孫悟空 MATCH MAKERS",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-dragonball-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "드래곤볼 초 고쿠 블랙 초사이어인 로제",
      nameEn: "Dragon Ball Super Goku Black Super Saiyan Rosé",
      nameJa: "『ドラゴンボール超』ゴクウブラック 超サイヤ人ロゼ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-dragonball-banpresto4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 글로리오사",
      nameEn: "One Piece Gloriosa",
      nameJa: "『ワンピース』グロリオーサ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto16.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 미스 버킹엄 스투시",
      nameEn: "One Piece Miss Buckingham Stussy",
      nameJa: "『ワンピース』ミス・バッキンガム・ステューシー",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto17.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "원피스 에드워드 뉴게이트 메가 워콜레",
      nameEn: "One Piece Edward Newgate Mega WCF",
      nameJa: "『ワンピース』エドワード・ニューゲート メガワーコレ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-onepiece-banpresto8.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 14)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月16日
    {
      nameKo: "어몽어스 SOFVIMATES vol.1",
      nameEn: "Among Us SOFVIMATES vol.1",
      nameJa: "『Among Us』SOFVIMATES vol.1",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-amongus-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 16)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "우마무스메 슈발그란",
      nameEn: "Uma Musume Shuvalgran",
      nameJa: "『ウマ娘』シュヴァルグラン",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-umamusume-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 16)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "우마무스메 비르시나",
      nameEn: "Uma Musume Virshina",
      nameJa: "『ウマ娘』ヴィルシーナ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-umamusume-banpresto4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 16)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "우마무스메 네오 유니버스",
      nameEn: "Uma Musume Neo Universe",
      nameJa: "『ウマ娘』ネオユニヴァース",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-umamusume-furyu.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 16)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "그 드레스업은 사랑을 한다 키타가와 마린",
      nameEn: "My Dress-Up Darling Kitagawa Marin",
      nameJa: "『その着せ替え人形は恋をする』喜多川海夢",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-bisquedoll-furyu2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 16)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月17日
    {
      nameKo: "디즈니 미키&프렌즈",
      nameEn: "Disney Mickey & Friends",
      nameJa: "『ディズニー』ミッキー＆フレンズ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-disney-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 17)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "디즈니 빌런즈",
      nameEn: "Disney Villains",
      nameJa: "『ディズニー』ヴィランズ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-disney-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 17)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月18日
    {
      nameKo: "드래곤볼 손오공 소년기",
      nameEn: "Dragon Ball Son Goku Childhood",
      nameJa: "『ドラゴンボール』孫悟空 少年期",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-dragonball-banpresto1.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 18)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "나루토 우즈마키 나루토&우치하 사스케",
      nameEn: "NARUTO Uzumaki Naruto & Uchiha Sasuke",
      nameJa: "『NARUTO』うずまきナルト&うちはサスケ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-naruto-banpresto4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 18)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "하츠네 미쿠 누들 스토퍼 스프링 ver.",
      nameEn: "Hatsune Miku Noodle Stopper Spring ver.",
      nameJa: "『初音ミク』ぬーどるストッパー スプリングver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-hatsunemiku-furyu4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 18)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月21日
    {
      nameKo: "나의 히어로 아카데미아 Figuno",
      nameEn: "My Hero Academia Figuno",
      nameJa: "『僕のヒーローアカデミア』Figuno",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/01/prize-202604-heroaca-banpresto2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 21)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月23日
    {
      nameKo: "원피스 BATTLE RECORD",
      nameEn: "One Piece BATTLE RECORD",
      nameJa: "『ワンピース』BATTLE RECORD",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto18.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 23)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月24日
    {
      nameKo: "원피스 로",
      nameEn: "One Piece Law",
      nameJa: "『ワンピース』ロー",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto19.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 24)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月25日
    {
      nameKo: "원피스 SOLID EDGE WORKS",
      nameEn: "One Piece SOLID EDGE WORKS",
      nameJa: "『ワンピース』SOLID EDGE WORKS",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-onepiece-banpresto12.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 25)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月29日
    {
      nameKo: "장송의 프리렌 Desktop Cute 여름 원피스",
      nameEn: "Frieren: Beyond Journey's End Desktop Cute Summer One-Piece",
      nameJa: "『葬送のフリーレン』Desktop Cute サマーワンピース",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-frieren-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 29)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "그 드레스업은 사랑을 한다 키타가와 마린 베로니카 ver.",
      nameEn: "My Dress-Up Darling Kitagawa Marin Veronica ver.",
      nameJa: "『その着せ替え人形は恋をする』喜多川海夢 ベロニカver.",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-bisquedoll-furyu2.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 29)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    {
      nameKo: "하츠네 미쿠 누들 스토퍼 10주년 기념",
      nameEn: "Hatsune Miku Noodle Stopper 10th Anniversary",
      nameJa: "『初音ミク』ぬーどるストッパー10周年記念",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/04/prize-202604-hatsunemiku-furyu4.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 29)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
    // 4月30日
    {
      nameKo: "마녀의 여행 일레이나",
      nameEn: "Wandering Witch: The Journey of Elaina Elaina",
      nameJa: "『魔女の旅々』イレイナ",
      imageUrl: "https://tokutame.net/wp-content/uploads/2026/03/prize-202604-frieren-banpresto3.webp",
      date: Timestamp.fromDate(new Date(2026, 3, 30)),
      time: "00:00",
      sourceUrl: src,
      createdAt: now,
      updatedAt: now,
    },
  ];

  console.log(`Importing ${figures.length} figures...`);
  for (const figure of figures) {
    const docRef = await adminDb.collection("figures").add(figure);
    console.log(`Added: ${figure.nameJa} (ID: ${docRef.id})`);
  }

  console.log(`\nDone! Imported ${figures.length} figures for April 2026.`);
}

importApril2026().catch(console.error);
